### ISSUE TITLE
Symfony2 file upload

### ISSUE THREAD

**Issue by linfiesto** [anlutro/php-curl#10]
How do I upload a file which is a symfony2 file object from my upload form to a web service using your library?

**Comment by anlutro** [comment]
I imagine you'd just use a [CURLFile](http://php.net/manual/en/curlfile.construct.php) - you should be able to follow the examples, just replace `curl_setopt` with `$request->setOption`.

**Comment by linfiesto** [comment]
Thanks. I solved the problem using the newRawRequest function and adding the curlfile array to the third parameter.
