### ISSUE TITLE
Not able to apply caching for JSON response

### ISSUE THREAD

**Issue by anil1712** [anlutro/php-curl#11]
Actually I din't want to hit the external API all the time, I want to set some caching(for 1hr or 30 min) kind of things for json responses, so please tell me how to achieve caching using your library or Laravel provides something out of the box for caching responses. 
FYI: I am using Lavarel 5.0

**Comment by anlutro** [comment]
Something like

```php
$this->apiService = new MyApiService($apiKey, $curl);
$stuff = Cache::remember('unique_cache_key', 30 /*minutes*/, function() {
    return $this->apiService->getStuff();
});
```

StackOverflow or the Laravel IRC channel is usually a better place to ask for help on stuff like this.
