### ISSUE TITLE
Problem while sending multipart/form-data request

### ISSUE THREAD

**Issue by anil1712** [anlutro/php-curl#14]
I am getting problem when attaching an image in my cURL request, so please give me some suggestion on this. Here is my code please let me know am I doing something wrong.
```
$content_type = 'application/json';
if($multipart==true) {
	$boundary = '';
	$boundary = $this->multipart_build_query($form_data, $boundary);
	$content_type = 'multipart/form-data; boundary=----' . $boundary;            
}

$request = cURL::newRawRequest('post', $url, $form_data)
	->setHeader('Content-Type', $content_type)	
$response =  $request->send();      


public function multipart_build_query($fields, $boundary) {
  $retval = '';
  foreach($fields as $key => $value){
	$retval .= '--' . $boundary . ' Content-Disposition: form-data; name=' .$key . ' " ' . $value . ' " ';
  }
  $retval .= "--$boundary--";
  return $retval;
}
```
Its working fine without image attachment, but don't know why its breaking after attachment.
Please get me out of it, I googled also but not able to get any solution.

**Comment by anlutro** [comment]
Your `multipart_build_query` looks off. It looks like it's used to build a request body, but you're using it to build the `content-type` header?

If you can create a code snippet using regular `curl_` function calls that work in your situation, we can work our way from there.

**Comment by anil1712** [comment]
Yes, I am using `multipart_build_query` to build a request body with multipart, can you please give me a simple demonstration with `multipart/form-data` image attachments with simple `curl_` function

**Comment by anlutro** [comment]
Not off the top of my head, I've never done it. I could google it but then again so could probably you.

This is just meant as a thin OOP wrapper on top of curl_ functions. You need to know how to use those to know how to use this library. If you need something with more batteries included or more user friendly, try Guzzle.

**Comment by anil1712** [comment]
thanks @anlutro for suggestion and quick reply, will check with Guzzle.
