### ISSUE TITLE
How cURL exception handle with try catch?

### ISSUE THREAD

**Issue by rashedshaon** [anlutro/php-curl#16]
In this purpose if server not response  or other issues, How cURL exception handle with try catch?

**Comment by anlutro** [comment]
Hey, thanks for bringing this up. Currently it throws a RuntimeException if `curl_exec() === false`, but I should change it so it's a specific cURLException.

You can also set the `CURLOPT_FAILONERROR` option to `true` to get exceptions when the HTTP status code is 400 or higher.

**Comment by anlutro** [comment]
I just tagged 1.1.0, in which the library throws an `anlutro/cURL/cURLException` if something goes wrong during the curl request. Hope that answers your question!
