### ISSUE TITLE
Post file

### ISSUE THREAD

**Issue by mathieutu** [anlutro/php-curl#17]
Hi, i would like to send a file wich contain json by your cURL library.
I've tried during 2 days, without success.

This is my cURL command :
```bash
curl -H "Content-Type: application/json" -X POST --data-binary '@MyFile' http://my_url
```
I've tried many things, the last one is : 

```php
$result = cURL::newJsonRequest('post', $url)
						->setHeader('content-type', 'application/json')
						->setOptions([CURLOPT_BINARYTRANSFER => true])
						->setOptions([CURLOPT_POSTFIELDS => ['file'=>'@/var/www/public/'.$file,'name'=>$file]])
						->send();

```
Moreover, there is no error, or I don't know where I can find them, but I don't received anything in the other side. (`Input::all()` return an empty array).

I should precize that a standard request like this one works fine : 
```php
$response = cURL::post($url, ['datas' => $array]);
```
Thank you for your answer !

**Comment by anlutro** [comment]
First off, `setOptions` will replace all existing options, so you'll either want to combine the two arrays into one method call, or use `setOption` instead.

**Comment by mathieutu** [comment]
this is the new code :
```php
$result = cURL::newJsonRequest('post', $url)
						->setHeader('content-type', 'application/json')
						->setOption(CURLOPT_BINARYTRANSFER, true)
						->setOption(CURLOPT_POSTFIELDS, ['file'=>'@/var/www/public/'.$file,'name'=>$file])
						->send();
```

**Comment by anlutro** [comment]
You can remove the `setHeader`, `newJsonRequest` sets it for you. You should also remove the `setOption(CURLOPT_POSTFIELDS, $data)` and pass the array as a third argument to `newJsonRequest` instead.

I'm also not sure how curl is supposed to handle that the request is both json and has file contents. I don't think you need the binary transfer option.

Can you provide a pure PHP curl script that successfully uploads the file?

**Comment by anlutro** [comment]
@mathieutu I did a bit of digging in on this. You can't use json/regular requests when uploading a file, you have to use `newRawRequest` or `rawPost`. See this test for an example: https://github.com/anlutro/php-curl/blob/4ef3dfc7b5ed76a253ac4a3e1db4e53c2b053831/tests/functional/cURLTest.php#L59-L65

The ability to add a file upload to a json/regular request is definitely something I should look into implementing if it's possible.

**Comment by mathieutu** [comment]
Ok, that work's like a standard file post (like by a HTML form), but not like the bash command.

With the command, I don't pass an array to cURL, but directly the file. 
I suppose that this is as I was sending the json directly.
Do you have an idea of how to do that ?

**Comment by anlutro** [comment]
Some quick googling brought me to this answer, which seems sensible: http://stackoverflow.com/a/4083908/2490608

Basically, either base64 encode/decode the file and send it as JSON, or make a separate request for the file. With that, I retract my previous statement, this is probably not something I should implement :)

**Comment by mathieutu** [comment]
ok, it seems weird that it's as complicated, as it's so easy to do with the bash command...

I think I will use the `system()` method and I'll stop be stuck on that.
Thank you for your help anyway!

**Comment by anlutro** [comment]
Well, the curl command you posted is not the same as the PHP code you were trying to do. With your curl command you're basically doing a raw request (like in the test I linked), you're just adding an application/json header despite the request not being JSON.
