### ISSUE TITLE
Connection timed out in Server

### ISSUE THREAD

**Issue by rashedshaon** [anlutro/php-curl#18]
It's working in localhost very well but when run on Web server then show me the following error.

RuntimeException in cURL.php line 239:
cURL request failed with error: Failed connect to 45.35.15.100:8080; Connection timed out

Is there have any settings to be changed?

**Comment by anlutro** [comment]
You should run the `curl` command on the server via SSH if you can to make sure the server can actually connect to that IP. You can also try tweaking the CURLOPT_CONNECTTIMEOUT and CURLOPT_TIMEOUT options. In the end, though, this error comes from curl, not my library.

**Comment by rashedshaon** [comment]
Thanks for your kind replay, if explain more that will be better for me, that you geuss.
I used,
$ch = curl_init();
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0); 
curl_setopt($ch, CURLOPT_TIMEOUT, 400); 
set_time_limit(0); 

After declaring
$curl = new cURL; 

But same as work on localhost not in server.

**Comment by anlutro** [comment]
Are you saying you did the following?

```php
$curl = new cURL;
$ch = curl_init();
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0); 
curl_setopt($ch, CURLOPT_TIMEOUT, 400); 
set_time_limit(0);
$curl->get('45.35.15.100:8080');
```

**Comment by rashedshaon** [comment]
Yes exactly and my curl url is related to this link  
 45.35.15.100

**Comment by anlutro** [comment]
Well that won't work at all... `$ch` is completely separate from the curl wrapper instance. Try again using something similar to what's shown as an example in the readme file:

```php
$request = $curl->newRequest('post', $url, ['foo' => 'bar'])
    ->setHeader('Accept-Charset', 'utf-8')
    ->setHeader('Accept-Language', 'en-US')
    ->setOption(CURLOPT_CAINFO, '/path/to/cert')
    ->setOption(CURLOPT_FOLLOWLOCATION, true);
$response = $request->send();
```

**Comment by rashedshaon** [comment]
Thanks for your help I solved the problem.
