### ISSUE TITLE
Can't send jsonPost request using newRequest function

### ISSUE THREAD

**Issue by sriraman** [anlutro/php-curl#31]
I want to send jsonPost request with `newRequest` function.

    cURL::newRequest('post',$request_url,['post'    =>  $request_body])
            ->setHeader('Content-Type', 'application/json')
            ->setHeader('Authorization', 'Bearer ACCESS_TOKEN')
            ->send();

`jsonPost` function is working fine. But, I can't add header information in `jsonPost` function.  

    cURL::jsonPost($request_url, ['post' => $request_body);

**Comment by anlutro** [comment]
You can use `newJsonRequest` instead of `newRequest`.

**Comment by sriraman** [comment]
Thank you. It is working fine.
