### ISSUE TITLE
Why not add proxy option?

### ISSUE THREAD

**Issue by JKingdom** [anlutro/php-curl#35]
Hi! I found you nice curl Lib.
I just have a simple request: can you add a proxy option to provide user to choice a proxy to curl?

**Comment by anlutro** [comment]
I don't want to add unnecessary abstractions. Adding a proxy to a curl connection should be as simple as working with the regular `curl` functions.

```php
// plain PHP
curl_setopt($ch, CURLOPT_PROXY, '1.2.3.4:8888');
curl_setopt($ch, CURLOPT_PROXYUSERPWD, 'user:pass');

// using my library
$curl->setOption(CURLOPT_PROXY, '1.2.3.4:8888');
$curl->setOption(CURLOPT_PROXYUSERPWD, 'user:pass');
```

**Comment by JKingdom** [comment]
thank you very much ` I just forget``
