### ISSUE TITLE
Call Https

### ISSUE THREAD

**Issue by ollakalla** [anlutro/php-curl#36]
when i try to call https instead of http i have this error:
cURL request failed with error [60]: SSL certificate problem: self signed certificate in certificate chain

**Comment by anlutro** [comment]
The problem is what it says. If you google "self signed certificate in certificate chain" you'll probably find some answers. You either need to install the CA you created yourself on the client machine, or use a publicly trusted CA. Maybe check out https://letsencrypt.org/
