### ISSUE TITLE
Support of ETag for API calls

### ISSUE THREAD

**Issue by hebabil** [anlutro/php-curl#44]
It would be interesting to support ETag for API calls (GET calls on resources).

The plugin would store the URI, the ETag and the response in a local cache (either a table, or file, or even use Laravel caching system). It would return the cached content if the ETag in the response header is the same than the one sent in the request.

What do you think about that ?

**Comment by anlutro** [comment]
I think that's beyond the scope of this library, which is to just be a simple wrapper for the `curl_` functions in PHP.

**Comment by hebabil** [comment]
OK, seems to me that there are already some specific headers like authentification via CURLOPT_USERPWD. Thought that it would be interesting to add the If none match header as well and a unified mechanism for cache. No problem at all, I will implement something on top of the curl lib.

Thanks anyway for the lib ;-)

**Comment by anlutro** [comment]
True, though those methods are just shortcuts for 2-3 other method calls. Adding ETag support would require some logic + integration with said cache layer, which could end up somewhat complex.

**Comment by hebabil** [comment]
Yeah I totally understand your point of view. Thanks again for the quick reply 👍
