### ISSUE TITLE
How to run this Curl

### ISSUE THREAD

**Issue by ollakalla** [anlutro/php-curl#45]
i have this curl and i don't know how to run it
`curl --user xps_client: --basic --data "username=test&password=test&scope=XPS_API_ALL&grant_type=access" http://100.19.33.12/oauth/token`

**Comment by anlutro** [comment]
What have you tried so far? Looks like a plain request with some POST data and basic authentication, all of which is covered in the readme.

**Comment by ollakalla** [comment]
Thanks i tried POST with basic authentication and works fine.
