### ISSUE TITLE
More relaxed PHPDoc for $data argument in cURL::newRequest and magic methods

### ISSUE THREAD

**Issue by djcvijic** [anlutro/php-curl#47]
In all of these methods, $data is type hinted as array. In fact, $data can also be a string, and perhap other types as well.

One solution is to type hint this parameter as **mixed** in all places. Another is to type hint it as **mixed** in _newRequest_, and just type hint it as **string** in the _raw_ magic methods.

Would you like me to submit a PR, or would you take care of it?

**Comment by anlutro** [comment]
That sounds very reasonable. If you could make a PR that'd be great, thanks!
