### ISSUE TITLE
Not working in Laravel 5.3

### ISSUE THREAD

**Issue by umairali** [anlutro/php-curl#48]
I am trying to use in laravel 5.3 but i am facing this error.

```
FatalErrorException in IndexController.php line 19: 
Class 'App\Http\Controllers\Web\cURL' not found
```

**Comment by anlutro** [comment]
This is completely unrelated to Laravel. If your class is in a different namespace than the class you want to use, you need to import the currect namespace with `use`. http://php.net/manual/en/language.namespaces.php

**Comment by umairali** [comment]
which namespace i will add for this in laravel

**Comment by umairali** [comment]
can you give me little example

**Comment by anlutro** [comment]
`use anlutro\cURL\Laravel\cURL;`

**Comment by umairali** [comment]
thanks now it's working
