### ISSUE TITLE
Method [target_url] not a valid HTTP method getting error 

### ISSUE THREAD

**Issue by cent040** [anlutro/php-curl#49]
error : BadMethodCallException in cURL.php line 358: Method [target_url] not a valid HTTP method.

My target_url looks like : ` cURL->__call('target_url', array('http://localhost:8000/upload/addfile?s=curl',`

need help.

**Comment by anlutro** [comment]
Why are you doing `__call`? Where did you get "target_url" from? Did you look at the [readme](https://github.com/anlutro/php-curl#usage)?

**Comment by cent040** [comment]
Hi, I got it. I was sending without headers. Thanks

I just want to confirm. If i give My Local PC file path for upload on server. will it work. it;s giving error. File could not open.  i.e (D:/files/test.zip) ..?

**Comment by anlutro** [comment]
Sorry, you're probably better off asking for basic programming help on stackoverflow or an IRC channel.
