### ISSUE TITLE
Problem with post  json using newJsonRequest function

### ISSUE THREAD

**Issue by ollakalla** [anlutro/php-curl#50]
I have try to send json using newJsonRequest but i have this error

> InvalidArgumentException: Method not a valid HTTP method

        $curl = new cURL;
        $url = $curl->buildUrl('http://127.0.0.1:8080',['post' => $result]);
        $response = $curl->newJsonRequest($url, ['post' => $result])
        ->setHeader('Content-Type', 'application/json')
        ->setHeader('Authorization', "bearer ".$access_token);
        $response = $request->send();

**Comment by anlutro** [comment]
When you use the `newRequest` methods you need to specify the HTTP method as the first argument.

**Comment by ollakalla** [comment]
but i don't use `newRequest` i use `newJsonRequest` to send json data and to add header to request

**Comment by anlutro** [comment]
The answer is still the same. You need to sepcify the HTTP method as the first argument.

**Comment by ollakalla** [comment]
Works fine now, Thanks

    $curl = new cURL;
    $url = $curl->buildUrl('http://127.0.0.1:8080', $result);
    $request = $curl->newJsonRequest('post',$url, $result)
    ->setHeader('Content-Type', 'application/json')
    ->setHeader('Authorization', "bearer ".$access_token);
    $response = $request->send();
