### ISSUE TITLE
HTTP Method "HEAD" not implemented correctly

### ISSUE THREAD

**Issue by manioc2015** [anlutro/php-curl#51]
The HTTP HEAD method is not implemented correctly. Instead of passing in HEAD as the CURLOPT_CUSTOMREQUEST, the CURLOPT_NOBODY option should be set instead. The bug results in slow and hanging HEAD requests.

Proposed Fix:
Line 275:
                } elseif ($method === 'head') {
                        curl_setopt($this->ch, CURLOPT_NOBODY, 1);

**Comment by anlutro** [comment]
Which server(s) are you seeing this behaviour with? I added a `HEAD` request test in the functional test and that doesn't seem to hang, but maybe that's just the PHP built-in server's behaviour.

I also wonder if setting `CURLOPT_NOBODY` should be done in other cases, like `DELETE`.

**Comment by manioc2015** [comment]
I tried https://www.google.com and https://www.amazon.com. Both just hangs and hangs. When I request a static mp3 file on an Apache server there is a noticeable delay.

**Comment by anlutro** [comment]
Thanks for letting me know and sorry for the slow response!
