### ISSUE TITLE
Delete Method not working in Curl

### ISSUE THREAD

**Issue by sharmavikram** [anlutro/php-curl#53]
It is a minor changes in cURL.php file. I'm trying to delete information from server. but it is not working because the issue in cUEL.php file.
Delete value is false. 
```
protected $methods = array(
		'get'     => false,
		'post'    => true,
		'put'     => true,
		'patch'   => true,
		'delete'  => false,
		'options' => false,
	);
```
 so please can you change it to true 
'delete'  => true,
**Reason**
In prepareRequest function only accept true method
```
if ($this->methods[$method] === true) {
}
```

**Comment by anlutro** [comment]
Why is this a problem? It's set to false because you're not supposed to send data with DELETE requests. What API are you working with that needs you to send data with a DELETE request?

**Comment by sharmavikram** [comment]
In DELETE request we can not add post fields data "CURLOPT_POSTFIELDS". with out any post fields it is working fine, but when i add some fields in DELETE request. it is not working.

**Comment by anlutro** [comment]
Sorry, forgot to reply here!

I was convinced that no one was using a POST body with a HTTP DELETE request, but some googling led me to discover that this is being done in some places, and the HTTP specifications don't disallow it, so I implemented the change (and reworked the HTTP method handling a bit in the process).

You should be able to test out the changes by adding `anlutro/curl:dev-master@dev` to your composer.json. I will tag a new stable release by the end of the week.

**Comment by sharmavikram** [comment]
Ok Thanks

**Comment by anlutro** [comment]
Tagged 1.4.4.
