### ISSUE TITLE
Method [setheaders] not a valid HTTP method.

### ISSUE THREAD

**Issue by WebCMS1** [anlutro/php-curl#55]
I am trying to set headers but it says "Method [setheaders] not a valid HTTP method."

Following is my code snippet.
        $curl = new \anlutro\cURL\cURL;
        $curl->post('http://localhost/test/php/file.php', ["image" => new \CurlFile(<path>, <mime type>, <name>)]);
        $curl->setHeader('Content-Type', 'multipart/form-data');
        $curl->setopt(CURLOPT_POST, true);
        $curl->setopt(CURLOPT_RETURNTRANSFER, true);
        $curl->setopt(CURLOPT_HEADER, true);
        $request->send()

**Comment by anlutro** [comment]
`setHeaders` is a method on the `Request` class, not `cURL`. You need to do `$request = $curl->newRequest(...)` and then call `setHeader`, `setOpt` etc. on the `$request` object.
