### ISSUE TITLE
How to send soap request?

### ISSUE THREAD

**Issue by shuk007** [anlutro/php-curl#56]
Hi!
Iam trying send SOAP request with your lib. 
https://stackoverflow.com/questions/7120586/soap-request-in-php-with-curl

**Comment by anlutro** [comment]
Hello and sorry for not responding! I was very busy the last few weeks and after that I simply forgot.

I'm not sure why you wouldn't use a dedicated SOAP client for this, but I imagine the stackoverflow answer has all the answers - you just need to replace `curl_setopt` with `$curl->setOption`. To pass headers, you either have to use `newRequest` and call `setHeaders` on the request object:

```php
$req = $curl->newRawRequest('POST', $url, $xmlstring);
$req->setHeaders([...]);
$response = $curl->sendRequest($req);
```

You can also call `$curl->setDefaultHeaders([...]);`, then you can do `$response = $curl->rawPost($url, $xmlstring)` but be aware that these headers will be sent with *every* request made with that `$curl` object.
