### ISSUE TITLE
cURL.php prepareRequest - wrong behavior

### ISSUE THREAD

**Issue by akoevroman** [anlutro/php-curl#61]
In several cases: $request->hasData() return true for empty(default) array of data.
This happens if $request->encodeData() return string '[]'
In this case, empty CURLOPT_POSTFIELDS are sent.

Also Request.php -> encodeData function has $encoding variable which is not defined.

**Comment by akoevroman** [comment]
This happens if $request->encodeData() return string '[]'

**Comment by djcvijic** [comment]
I recently implemented this behaviour so maybe I can help.

This is important for JSON communication, because empty arrays and empty objects are encoded to '[]' and '{}' respectively, and this is NON-empty data, and hasData MUST be true.

Please state your exact usage, the expected result, and the actual result, so that we may find a universal solution.

**Comment by anlutro** [comment]
What @djcvijic wrote is indeed true!

@akoevroman what version of the library are you using? This should be fixed in 1.4.5 or higher.

I pushed a commit for the `$encoding` variable issue you mentioned, though that default case should never actually trigger so I don't think it's a fatal bug.

**Comment by akoevroman** [comment]
Version 1.4.6

Example:
```
$request = cURL::newJsonRequest('get', $this->requestUrl);
$response = $request->send();
```
so then we go to lib
```
public function newJsonRequest($method, $url, $data = array())
	{
		return $this->newRequest($method, $url, $data, Request::ENCODING_JSON);
	}
```
array() by default

then
`	public function newRequest($method, $url, $data = array(), $encoding = Request::ENCODING_QUERY)`
also array

Finaly:

```
array->
$request->setData($data);
->
$this->data = $data;
->
$request->hasData()
-> '[]' returned
```
maybe... i did something wrong?

Of course, "'[]' returned" is not a critical error but some API denied empty array in POST fields and return a response that appropriate data are expected.

**Comment by anlutro** [comment]
That's an annoying bug. See the commit message of https://github.com/anlutro/php-curl/commit/a2809a2a64cacf83fa7b9e5365b7613635049ef6 for more information. I've tagged `1.4.7` with the fix.

**Comment by djcvijic** [comment]
Yes, the recent fix I made was to cover POST-like request methods, but then GET was broken in the process. 1.4.7 looks good to me.
